### ISSUE TITLE
pages for tagcloud, categories, and archives

### ISSUE THREAD

**Issue by pwm1234** [abakan-zz/ablog#66]
First let me say thanks for the great blog engine! I was using Nikola, but I found it awkward switching between using Nikola for blog content Sphinx for documentation. So I believe ablog will be a great tool for me.

Now my question: how can I get pages that have the same content as the html_sidebars `tagcloud.html`, `categories.html`, and `archives.html`? I know that each one has their corresponding generated page, but what I would like is a page that has the same summary content as is placed in the sidebar. I believe that doing so would be a simple exercise with sphinx customization and templating, but, unfortunately, that is beyond my skill level right now. (This is another reason why I like ablog, skills I learn for the blogging engine will equally apply for my core sphinx usage.)

Thanks,
Phil

**Comment by pwm1234** [comment]
I discovered an answer to this issue. I posted my solution [How to get an ablog sphinx page with sidebar contents](http://stackoverflow.com/q/37073532/3154588) on stackoverflow.

**Comment by lakhman** [comment]
+1 with the thanks, I just started using this, this is awesome!! 👍 

Managed to get it working with my own theme, no issues, just wanted to say thanks to the dev!

I used the following to render a sidebar (just temporary - i'll customize as required):

    # Pop me in your layout.html or wherever to render the default sidebar.
    {{ sidebar() }}
